### ISSUE TITLE
Hall-Carpet-Rotations empty value doesn't work and crashes server

### ISSUE THREAD

**Issue by AnatomyKing** [PoiXson/pxnBackrooms-mirror#12]
```yml
  Blocks:
    SubFloor: minecraft:oak_planks
    SubCeiling: minecraft:red_concrete_powder
    Hall-Wall: minecraft:stripped_spruce_wood
    Hall-Carpet: minecraft:black_glazed_terracotta
    Hall-Carpet-Rotations: news
    Hall-Ceiling: minecraft:polished_diorite
```
I tried almost every combination. But I can't get the empty value to work with no rotation blocks. It will still crash my server

combinations I tried,

```yml
    Hall-Carpet: minecraft:red_wool
    Hall-Carpet-Rotations: 
```
```yml
    Hall-Carpet: minecraft:red_wool
    Hall-Carpet-Rotations: ""
```
```yml
    Hall-Carpet: minecraft:red_wool
    Hall-Carpet-Rotations: ''
```
```yml
    Hall-Carpet: minecraft:red_wool
    Hall-Carpet-Rotations: none
```
```yml
    Hall-Carpet: minecraft:red_wool
    # Hall-Carpet-Rotations: news
```

**Comment by lorenzop** [comment]
I think what's happening is leaving it blank actually sets it to the default value. it does this so it has a default value when creating or updating the config file, when that entry doesn't exist yet. how do I fix this?.. could use the word none, or could use a dash -. lets go with both. can set this line to '-' or none.

this is fixed

**Comment by AnatomyKing** [comment]
> I think what's happening is leaving it blank actually sets it to the default value. it does this so it has a default value when creating or updating the config file, when that entry doesn't exist yet. how do I fix this?.. could use the word none, or could use a dash -. lets go with both. can set this line to '-' or none.
> 
> this is fixed

Yess!! it is working now!! thank you!!

combinations that worked,

```yml

  Blocks:
    Hall-Carpet: minecraft:note_block
    Hall-Carpet-Rotations: '-'
```
    
```yml
  Blocks:
    Hall-Carpet: minecraft:red_wool
    Hall-Carpet-Rotations: 'none'
```

```yml
  Blocks:
    Hall-Carpet: minecraft:note_block
    Hall-Carpet-Rotations: 'null'
```
