### ISSUE TITLE
Poolroom tunnels don't generate

### ISSUE THREAD

**Issue by AnatomyKing** [PoiXson/pxnBackrooms-mirror#33]
I wanted to improve the poolroom generation. I also saw that you added `Thresh-Tunnel:`

I currently have these parameters 

```
Level_037:
  Enable-Gen: true
  Enable-Top: true
  Level-Y: 65
  Level-Height: 14
  Water-Depth: 4
  SubFloor: 3
  SubCeiling: 3
  Noise-Room-Freq: 1.5
  Noise-Room-Octave: 7
  Noise-Room-Gain: 4.0
  Noise-Room-Strength: 6.0
  Noise-Tunnel-Freq: 0.05
  Noise-Tunnel-Strength: 8.0
  Noise-Portal-Lobby-Freq: 0.02
  Noise-Portal-Lobby-Octave: 3
  Noise-Portal-Hotel-Freq: 0.005
  Thresh-Room: 0.2
  Thresh-Portal: 0.5
  Thresh-Tunnel: 1.0
```

but I don't think the `Thresh-Tunnel` does anything, since the tunnels don't generate anymore.

These are the tunnels I am talking about,
![2024-05-09_02 36 59](https://github.com/PoiXson/pxnBackrooms-mirror/assets/128033443/a736d6f5-3a44-4943-98ba-72c24e4ff33f)
![2024-05-09_02 38 29](https://github.com/PoiXson/pxnBackrooms-mirror/assets/128033443/6cf8f921-d046-4206-bfe0-b7ae61ec641e)

But for some reason in the latest build they don't generate anymore, here is an example to prove it
both gens use the same seed and parameters. The seed: `757781` and the parameters from above.
coords: `-10184 74 435`

pxnBackrooms v0.1.48 and pxnPluginLib v4.0.58
![2024-05-09_03 09 42](https://github.com/PoiXson/pxnBackrooms-mirror/assets/128033443/456cc75f-fa79-4f41-82b6-f111717a3ea0)

pxnBackrooms v0.1.53 and pxnPluginLib v4.0.59
![2024-05-09_03 10 09](https://github.com/PoiXson/pxnBackrooms-mirror/assets/128033443/93d6034e-ea30-4d1f-9307-292e1421abb7)

****As you can see the tunnel doesn't generate in the latest build. I hope this can be fixed, since it really added a lot to the poolrooms, esspically now it's possible to increase it with `Thresh-Tunnel` the gen would look so awesome with  a lot of these tunnels in it!****
