### ISSUE TITLE
crazy quantities of the portal from 5 to 19

### ISSUE THREAD

**Issue by AnatomyKing** [PoiXson/pxnBackrooms-mirror#34]
![2024-05-17_20 30 39](https://github.com/PoiXson/pxnBackrooms-mirror/assets/128033443/cf9529c0-3089-4760-a109-64cdcb9111ae)

when I use blockstates in the Wall and Floor config in level 19, it wil generate crazy amounts of 5 to 19 portals, here are some examples what I mean.

with these configs it will generate crazy amounts
```yml
Level_019:
  Wall: minecraft:note_block[instrument=bass,note=2,powered=false]
  Floor: minecraft:note_block[instrument=bass,note=3,powered=false]
  Beam: minecraft:spruce_wood
  Lamp: minecraft:lantern[hanging=true]
```

```yml
Level_019:
  Wall: minecraft:note_block[instrument=bass,note=2,powered=false]
  Floor: minecraft:birch_planks
  Beam: minecraft:spruce_wood
  Lamp: minecraft:lantern[hanging=true]
```

```yml
Level_019:
  Wall: minecraft:birch_planks
  Floor: minecraft:note_block[instrument=bass,note=3,powered=false]
  Beam: minecraft:spruce_wood
  Lamp: minecraft:lantern[hanging=true]
```

So for some reason both Wall and Floor from level 19 can't have blockstates otherwise the portal will generate in crazy amounts. I also played around with `Noise-Stairs-Freq` since I thought this controlled the portal generation from 5 to 19, But I doubt it does anything.

 this config works perfectly
```yml
Level_019:
  Wall: minecraft:birch_planks
  Floor: minecraft:birch_planks
  Beam: minecraft:spruce_wood
  Lamp: minecraft:lantern[hanging=true]
```
because Wall and Floor now both have a block without blockstates.

I hope this can be fixed soon, since it's quite annoying bug
